# Generated by Django 3.1.2 on 2020-10-25 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('RPA', 'RPA'), ('PD', 'Produto Digital'), ('ANA', 'Analytics'), ('BPM', 'BPM')], max_length=3)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='backend.lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='backend.statuslead'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.lead')),
            ],
        ),
    ]
