# Generated by Django 3.1.2 on 2020-10-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
